version: '3.8'
services:
  vllm-heavy:
    image: vllm/vllm-openai:latest
    container_name: vllm_heavy_exaone-32b-awq
    runtime: nvidia
    ports:
    - 8000:8000
    environment:
    - CUDA_VISIBLE_DEVICES=0
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-3.0-32B-Instruct-AWQ --gpu-memory-utilization
      0.95 --max-model-len 4096 --port 8000 --quantization awq
  vllm-light-0:
    image: vllm/vllm-openai:latest
    container_name: vllm_light_exaone-1.2b_0
    runtime: nvidia
    ports:
    - 8001:8000
    environment:
    - CUDA_VISIBLE_DEVICES=1
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-1.2B --gpu-memory-utilization 0.19 --max-model-len
      4096 --port 8000
  vllm-light-1:
    image: vllm/vllm-openai:latest
    container_name: vllm_light_exaone-1.2b_1
    runtime: nvidia
    ports:
    - 8002:8000
    environment:
    - CUDA_VISIBLE_DEVICES=1
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-1.2B --gpu-memory-utilization 0.19 --max-model-len
      4096 --port 8000
  vllm-light-2:
    image: vllm/vllm-openai:latest
    container_name: vllm_light_exaone-1.2b_2
    runtime: nvidia
    ports:
    - 8003:8000
    environment:
    - CUDA_VISIBLE_DEVICES=1
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-1.2B --gpu-memory-utilization 0.19 --max-model-len
      4096 --port 8000
  vllm-light-3:
    image: vllm/vllm-openai:latest
    container_name: vllm_light_exaone-1.2b_3
    runtime: nvidia
    ports:
    - 8004:8000
    environment:
    - CUDA_VISIBLE_DEVICES=1
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-1.2B --gpu-memory-utilization 0.19 --max-model-len
      4096 --port 8000
  vllm-light-4:
    image: vllm/vllm-openai:latest
    container_name: vllm_light_exaone-1.2b_4
    runtime: nvidia
    ports:
    - 8005:8000
    environment:
    - CUDA_VISIBLE_DEVICES=1
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    command: --model LGAI-EXAONE/EXAONE-1.2B --gpu-memory-utilization 0.19 --max-model-len
      4096 --port 8000
