
/******************************************************************************************
 * EASYEDA FULL AUTOMATION SCRIPT (PLACEMENT + WIRING)
 * Generated by Jules' Python Pipeline
 ******************************************************************************************/
(function() {
    console.log("Starting full automation script...");
    const data = {
    "parts": [
        {
            "cnum": "C12345",
            "ref": "R1"
        },
        {
            "cnum": "C10086",
            "ref": "C1"
        },
        {
            "cnum": "C17414",
            "ref": "R2"
        },
        {
            "cnum": "C967822",
            "ref": "U1"
        }
    ],
    "netlist": {
        "NET_VCC": [
            {
                "ref": "U1",
                "pin": "3V3"
            },
            {
                "ref": "C1",
                "pin": "1"
            }
        ],
        "NET_GND": [
            {
                "ref": "U1",
                "pin": "GND"
            },
            {
                "ref": "C1",
                "pin": "2"
            }
        ],
        "NET_LED_CTRL": [
            {
                "ref": "U1",
                "pin": "GPIO22"
            },
            {
                "ref": "R1",
                "pin": "1"
            }
        ],
        "NET_TO_R2": [
            {
                "ref": "R1",
                "pin": "2"
            },
            {
                "ref": "R2",
                "pin": "1"
            }
        ]
    }
};
    const componentGIds = {}; // Map for ref -> gId

    // 1. Place all components
    console.log("Placing components...");
    let x = 200, y = 200, i = 0;
    data.parts.forEach(p => {
        const gId = `jules_${p.ref}_${new Date().getTime()}`; // Ensure unique gId
        componentGIds[p.ref] = gId;
        api('createShape', {
            shapeType: 'schlib', from: 'LCSC', title: p.cnum,
            gId: gId, x: x + (i % 4) * 250, y: y + Math.floor(i / 4) * 200
        });
        i++;
    });

    // Delay to allow UI to update with placed components
    setTimeout(() => {
        console.log("Starting wiring process...");
        const allShapes = api('getSource', {type: 'json'});
        const pinCoordsCache = {}; // Cache for pin coordinates: 'U1_1': {x: 123, y: 456}

        // Pre-process and cache all pin coordinates
        for (const gId in allShapes.schlib) {
            const component = allShapes.schlib[gId];
            const componentRef = component.head?.annotation?.find(a => a.type === 'prefix')?.text;
            if (!componentRef || !component.head.pin) continue;

            const cx = parseFloat(component.head.x);
            const cy = parseFloat(component.head.y);

            for (const pinId in component.head.pin) {
                const pin = component.head.pin[pinId];
                const pinKey = `${componentRef}_${pin.number}`;
                pinCoordsCache[pinKey] = { x: cx + parseFloat(pin.x), y: cy + parseFloat(pin.y) };
            }
        }

        // 2. Draw wires for all nets
        for (const netName in data.netlist) {
            const connections = data.netlist[netName];
            const points = [];
            connections.forEach(conn => {
                const pinKey = `${conn.ref}_${conn.pin}`;
                if (pinCoordsCache[pinKey]) {
                    points.push(pinCoordsCache[pinKey]);
                } else {
                    console.error(`Could not find coordinates for pin: ${pinKey}`);
                }
            });

            if (points.length < 2) continue;

            // Simple daisy-chain wiring
            for (let i = 0; i < points.length - 1; i++) {
                const start = points[i];
                const end = points[i + 1];
                api('createShape', {
                    shapeType: 'wire',
                    jsonCache: {
                        points: [{x: start.x, y: start.y}, {x: end.x, y: end.y}],
                        stroke: "#0000FF", "stroke-width": "1"
                    }
                });
            }
        }
        alert('Full automation script finished!');
        console.log("Script finished.");
    }, 2000); // Increased delay for stability

})();
